#!/bin/sh

log=/dev/null

echo "Running post-checkout command" >> $log

if [[ ! -f .gituntrack ]] ; then
	echo "No .gituntrack file" >> $log
    exit
fi

#previous_gituntrack=git show HEAD:.gituntrack
#
#while IFS='' read -r line || [[ -n "$line" ]]; do
#    if [ -f $line ];
#    then
#		git update-index --no-assume-unchanged "$line"
#    fi
#done <<< "$previous_gituntrack"

# Loop through the current version of the file and untrack all of the files.

while IFS='' read -r line || [[ -n "$line" ]]; do
    if [ -f "$line" ] && [ ! -z "$line" ];
    then
	    git ls-files "$line" --error-unmatch
		rc=$?
		if [[ $rc = 0 ]];
		then
			echo "Processing $line" >> $log
            git update-index --assume-unchanged "$line"
		else
			echo "Skipping $line because it's already untracked in git" >> $log
		fi
	else
		echo "Skipping $line because it's not a real file" >> $log
    fi
done < .gituntrack
