#!/bin/sh

#log=/dev/null
log=pre-commit.log.txt

echo "Running pre-commit hook" >> $log

echo "Unapplying state from previous version of .gituntrack" >> $log

previous_gituntrack=`git show HEAD:.gituntrack`

# Loop through the previous version of the file and track all of the files.

while IFS='' read -r line || [[ -n "$line" ]]; do
    if [ -f "$line" ] && [ ! -z "$line" ];
    then
		echo "Stop assuming unchanged: $line" >> $log
		git update-index --no-assume-unchanged "$line"
	else
		echo "Skipping $line because it's not a real file" >> $log
    fi
done <<< "$previous_gituntrack"

if [[ ! -f .gituntrack ]] ; then
	echo "No .gituntrack file" >> $log
    exit
fi

echo "Applying state from current version of .gituntrack" >> $log

# Loop through the current version of the file and untrack all of the files.

while IFS='' read -r line || [[ -n "$line" ]]; do
    if [ -f "$line" ] && [ ! -z "$line" ];
    then
	    git ls-files "$line" --error-unmatch
		rc=$?
		if [[ $rc = 0 ]];
		then
			echo "Start assuming unchanged: $line" >> $log
            git update-index --assume-unchanged "$line"
		else
			echo "Skipping $line because it's already untracked in git" >> $log
		fi
	else
		echo "Skipping $line because it's not a real file" >> $log
    fi
done < .gituntrack
