#!/bin/sh

if [[ ! -f .gituntrack ]] ; then
    exit
fi

previous_gituntrack=git show HEAD:.gituntrack

while IFS='' read -r line || [[ -n "$line" ]]; do
    if [ -f $line ];
    then
		git update-index --no-assume-unchanged "$line"
    fi
done <<< "$previous_gituntrack"

# Loop through the current version of the file and untrack all of the files.

while IFS='' read -r line || [[ -n "$line" ]]; do
    if [ -f $line ];
    then
	    git ls-files file_name --error-unmatch
		rc=$?
		if [[ $rc == 0 ]];
		then
            git update-index --assume-unchanged "$line"
		fi
    fi
done < .gituntrack
